---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "isoseq3_dedup"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::isoseq3=3.8.2"
